// @klip/eslint-config/next.js
// Config for the Next.js app. `eslint-config-next` doesn't ship a flat
// config yet, so we bridge it in via FlatCompat.
import { FlatCompat } from "@eslint/eslintrc";
import base from "./base.js";

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

/** @type {import("eslint").Linter.Config[]} */
export default [
  ...base,
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // Next's own config already covers React/JSX + web-vitals concerns.
      // Add project-specific overrides here as they come up.
    },
  },
  {
    // Auto-generated by `next dev`/`next build` on every run — never hand-edited,
    // so it shouldn't be linted (its triple-slash reference trips
    // @typescript-eslint/triple-slash-reference otherwise).
    ignores: ["next-env.d.ts"],
  },
];
